
DROP TABLE IF EXISTS nameusage;
CREATE TABLE nameusage (
    `domain` TEXT,
    `kingdom` TEXT,
    `subkingdom` TEXT,
    `phylum` TEXT,
    `subphylum` TEXT,
    `infraphylum` TEXT,
    `parvphylum` TEXT,
    `megaclass` TEXT,
    `class` TEXT,
    `subclass` TEXT,
    `order` TEXT,
    `suborder` TEXT,
    `infraorder` TEXT,
    `parvorder` TEXT,
    `superfamily` TEXT,
    `epifamily` TEXT,
    `family` TEXT,
    `subfamily` TEXT,
    `tribe` TEXT,
    `subtribe` TEXT,
    `genus` TEXT,
    `subgenus` TEXT,
    `species` TEXT,
    `subspecies` TEXT,
    `infraspecies` TEXT,
    `infraspecific_name` TEXT,
    `form` TEXT,
    `variety` TEXT,
    `aberration` TEXT,
    `other` TEXT,
    `species_aggregate` TEXT,
    `proles` TEXT,
    `dataset_id` TEXT,
    `dataset_alias` TEXT,
    `dataset_link` TEXT,
    `parent_id` TEXT,
    `taxon_id` TEXT,
    `name_id` TEXT,
    `rank` TEXT,
    `accepted_id` TEXT,
    `accepted_name` TEXT,
    `accepted_author` TEXT,
    `scientific_name` TEXT,
    `authorship` TEXT,
    `authors` TEXT,
    `year` TEXT,
    `status` TEXT,
    `extinct` BOOLEAN,
    `temporal_range_start` TEXT,
    `temporal_range_end` TEXT,
    `link` TEXT,
    `reference_id` REFERENCES reference(reference_id),
    `identifiers` TEXT,
    FOREIGN KEY(`reference_id`) REFERENCES reference(`reference_id`),
    FOREIGN KEY(`dataset_id`) REFERENCES dataset(`dataset_id`)
);

DROP TABLE IF EXISTS reference;
CREATE TABLE reference (
    `reference_id` TEXT PRIMARY KEY,
    `source_id` TEXT,
    `type` TEXT,
    `authors` TEXT,
    `year` TEXT,
    `title` TEXT,
    `citation` TEXT,
    `journal` TEXT,
    `volume` TEXT,
    `page` TEXT
);

DROP TABLE IF EXISTS dataset;
CREATE TABLE dataset (
    `dataset_id` TEXT PRIMARY KEY,
    `alias` TEXT,
    `title` TEXT,
    `issued` TEXT,
    `version` TEXT,
    `description` TEXT,
    `contact` TEXT,
    `creator` TEXT,
    `editor` TEXT,
    `publisher` TEXT,
    `contributor` TEXT,
    `doi` TEXT,
    `license` TEXT,
    `geographic_scope` TEXT,
    `temporal_scope` TEXT,
    `taxonomic_scope` TEXT,
    `confidence` TEXT,
    `completeness` TEXT,
    `logo` TEXT,
    `created` TEXT,
    `modified` TEXT,
    `type` TEXT,
    `origin` TEXT
);